apiVersion: api.huisebug.org/v1
kind: LogFile
metadata:
  name: fec
  namespace: logfile-operator-system
spec:
  programmenum: 2
  elastic_password: "es8123456"
  kibana_password: "es8123456"
  storageClassName: "nfs-storageclass"
  resourcestorage:
    elasticsearch: "200Gi"
    zookeeper: "10Gi"
    kafka: "8Gi"
  nodePorts:
    elasticsearch: 31199
    kibana: 31056

