apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    version: v1
  name: sidecar-test
  namespace: sidecar-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        logfile.huisebug.org/log1: /var/log/nginx/*.log
        logfile.huisebug.org/log2: /etc/pro/kkk/111.log
      labels:
        app: nginx
        version: v1
        # pod-admission-webhook-injection: "false"
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    version: v1
  name: sidecar-test
  namespace: sidecar-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30256
  selector:
    app: nginx
  #type: ClusterIP
  type: NodePort