
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-mysql
    version: v1
  name: nginx-mysql
  namespace: sidecar-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31052
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 31053
  selector:
    app: nginx-mysql
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-mysql
    version: v1  
  name: nginx-mysql
  namespace: sidecar-test  
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: nginx-mysql
      version: v1

  template:
    metadata:
      annotations:
        logfile.huisebug.org/log1: /var/log/nginx/*.log    
        logfile.huisebug.org/log2: /var/log/mysql/general_sql.log
      labels:
        app: nginx-mysql
        version: v1
    spec:
      initContainers:
      - name: genhtml
        image: nginx
        command:
        - bash 
        - -c 
        args:
        - 'mkdir -p /tmp && touch /tmp/index.html && hostname > /tmp/index.html'
        volumeMounts:
        - name: html
          mountPath: "/tmp"
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the postStart handler >> /usr/share/nginx/html/index.html"]          
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html  
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      - image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD    
          value: "123456"
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP         
        volumeMounts:
        - mountPath: /etc/my.cnf
          name: mysql
          subPath: my.cnf 
        - mountPath: /var/log/mysql
          name: log
          subPath: mysql-log          
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true   
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: html
        emptyDir: {}
      - configMap:
          defaultMode: 420
          name: mysql
        name: mysql
      - name: log
        persistentVolumeClaim:
          claimName: sidecar-test       

---

apiVersion: v1
data:
  my.cnf: |-
    [mysqld]
    max_connections=1000
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql
    symbolic-links=0

    #开启记录mysql操作语句
    general_log=1
    general_log_file=/var/log/mysql/general_sql.log
    #设置时区
    default-time-zone = '+8:00' 
    #设置日志时区
    log_timestamps = SYSTEM

    pid-file=/var/run/mysqld/mysqld.pid
    [client]
    socket=/var/run/mysqld/mysqld.sock

    !includedir /etc/mysql/conf.d/
          
kind: ConfigMap
metadata:
  name: mysql
  namespace: sidecar-test