---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-api-huisebug-org-v1-logfile
  failurePolicy: Fail
  name: mlogfile.kb.io
  rules:
  - apiGroups:
    - api.huisebug.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - logfiles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-huisebug-core-v1-pod
  failurePolicy: Fail
  name: mhuisebugpod.kb.io
  namespaceSelector:
    matchLabels:
      pod-admission-webhook-injection: enabled  
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: "Namespaced"
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-api-huisebug-org-v1-logfile
  failurePolicy: Fail
  name: vlogfile.kb.io
  rules:
  - apiGroups:
    - api.huisebug.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - logfiles
  sideEffects: None
